// This file is the main entrypoint for compiled modules.
import {CompiledModule} from './compiled-code';
import Executor from './executor';
import NodePlatform from './node-platform';

// Generated by codegen.
declare var compiledModule: CompiledModule;

async function run() {
  const executor = new Executor(new NodePlatform());
  return await executor.executeModule(compiledModule);
}

export default run;

if (require.main === module) {
  run();
}
